(() => {
  "use strict";
  const root = document.querySelector("[data-guide-app]");
  const visionSections = document.querySelectorAll("[data-vision-experience]");
  if (!root && !visionSections.length) return;
  const locales = ["ko","en","de","es","fr","ja","zh-Hans","zh-Hant"];
  const locale = () => locales.includes(document.documentElement.lang) ? document.documentElement.lang : "en";
  const json = async path => { const r=await fetch(path,{cache:"no-store"}); if(!r.ok)throw Error(path); return r.json(); };
  const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
  const button=(text,action,cls="")=>{const b=el("button",cls,text);b.type="button";b.addEventListener("click",action);return b;};
  const link=(text,href)=>{const a=el("a","sim-link",text);a.href=href;return a;};
  let map,translations,demos,catalog,release,appCatalog;
  let view="steam",mode="demo",photo=0,lastFocus,appPlatform="mac";
  const initial=()=>({renderer:"D3DMetal - NVIDIA",fg:false,frameCheck:false,gameMode:true,microphone:false,network:"Ethernet",vram:"auto",pointer:false,mapping:false,command:"Ctrl",option:"Alt",control:"Ctrl",quitKeys:false,switchKeys:false,spaces:false,screenshots:false,awdl:true,library:null,exe:null,exeRenderer:"Wine",profileRoot:false,setup:0,analysis:null,theme:"system",retention:"30",sync:"auto"});
  let state=initial();
  const T=key=>translations[locale()]?.[key]??translations.en?.[key]??key;
  const D=key=>demos[locale()]?.[key]??demos.en[key];
  const W=key=>window.ForgePlaySite?.message(key)||key;
  const prefs=["general","input","awdl","prefix","data","about"];
  const steam=["steam","fg","storage","components"];
  const nav=["setup","steam","profiles","exe","catalog","dashboard","diagnostics","general","vision","why","sponsors","apps"];
  const name=id=>id==="vision"?"Vision Pro":T(map.views[id].title);
  const note=(parent,text,cls="")=>parent.append(el("p",`sim-note ${cls}`,String(text).replaceAll('\\n','\n')));
  const field=(parent,label,node)=>{const row=el("label","sim-field");row.append(el("span","",label),node);parent.append(row);};
  const picker=(key,values,label)=>{const select=el("select");select.id=`sim-select-${key}`;select.setAttribute("aria-label",label);values.forEach(([value,text])=>{const option=el("option","",text);option.value=value;option.selected=state[key]===value;select.append(option);});select.addEventListener("change",()=>{state[key]=select.value;if(key==="theme")render();});return select;};
  const card=(title)=>{const c=el("section","sim-card");c.append(el("h4","",title));return c;};
  const actionRow=(parent,...actions)=>{const row=el("div","sim-actions");row.append(...actions);parent.append(row);};
  const toggle=(parent,label,key,action)=>{const row=el("div","sim-toggle-row");const id=`sim-${key}`;const text=el("span","",label);text.id=`${id}-label`;const b=button("",()=>{state[key]=!state[key];if(action)action();render();},"sim-switch");b.id=id;b.setAttribute("role","switch");b.setAttribute("aria-checked",String(state[key]));b.setAttribute("aria-labelledby",text.id);b.append(el("span"));row.append(text,b);parent.append(row);};
  let dialog;
  const show=(title,body,choices=[])=>{
    lastFocus=document.activeElement;dialog.replaceChildren();const header=el("div","sim-dialog-head");const heading=el("h3","",title);heading.id="sim-dialog-title";header.append(heading,button(D("close"),()=>dialog.close()));dialog.append(header,el("p","",body));
    if(choices.length){const list=el("div","sim-choices");choices.forEach(([text,action])=>list.append(button(text,()=>{dialog.close();action();render();})));dialog.append(list);}dialog.showModal();
  };
  const explain=(key)=>show(D("example"),D(key));
  const change=id=>{if(!map.views[id]&&id!=="vision")return;view=id;mode="demo";render();};
  const fgCard=()=>{
    const c=card(T("Frame Generation (베타)"));toggle(c,T("Frame Generation (베타)"),"fg",()=>{state.frameCheck=state.fg;});
    if(state.fg){const fps=el("div","sim-actions");fps.append(button("120 FPS",()=>show("120 FPS",T(map.views.fg.notes[1])),"sim-selected"));for(const value of [144,240]){const b=button(`${value} FPS · ${T("준비 중")}`,()=>{});b.disabled=true;fps.append(b);}c.append(fps);toggle(c,"Frame Check","frameCheck");const legend=el("div","sim-fps-legend");for(const term of ["Target","Original","Generated","Displayed"])legend.append(el("span","",term));c.append(legend);note(c,T(map.views.fg.notes[2]));}
    note(c,T(map.views.fg.notes[3]));return c;
  };
  const steamView=parent=>{
    const launch=card(T("Steam 실행"));actionRow(launch,button(`▶ ${T("Steam 실행")}`,()=>explain("launch"),"sim-primary"),button(T("설정 저장"),()=>explain("saved")),button(T("저장공간 관리"),()=>change("storage")),button(T("Wine 강제 종료"),()=>show(T("Wine 강제 종료"),D("notice"))));note(launch,D("example"));
    const renderers=el("div","sim-renderers");for(const [r,api]of [["D3DMetal - NVIDIA","DX11/12 · 64-bit"],["DXMT","DX10/11"],["DXVK","DX10/11"],["WineD3D","D3D9 · 32-bit"]]){const b=button("",()=>{state.renderer=r;state.fg=false;state.frameCheck=false;render();},state.renderer===r?"sim-selected":"");b.setAttribute("aria-pressed",String(state.renderer===r));b.append(el("strong","",r),el("small","",api));renderers.append(b);}launch.append(renderers);parent.append(launch,fgCard());
    const options=card(T("다음 Steam 실행 설정"));toggle(options,"Game Mode","gameMode");field(options,T("네트워크 (베타)"),picker("network",[["Ethernet",T("Ethernet 호환성")],["Wi-Fi",T("Wi-Fi 호환성")]],T("네트워크 (베타)")));toggle(options,T("오디오 입력 (베타)"),"microphone");field(options,T("게임 비디오 메모리 (베타)"),picker("vram",[["auto",T("자동")],...['2','4','8','12','16'].map(n=>[n,`${n} GB`])],T("게임 비디오 메모리 (베타)")));actionRow(options,button(T("컨트롤러 확인"),()=>show(T("컨트롤러 확인"),T("macOS의 Game Controller 발견 단계와 Windows 세션 확인 단계를 분리해 점검합니다."))));parent.append(options);
  };
  const storageView=parent=>{const c=card(T("Steam 저장공간 연결"));note(c,T(map.views.storage.notes[0]));actionRow(c,button(T("외장 드라이브/폴더 연결"),()=>show(D("choose"),D("fileHint"),[[D("existing"),()=>{state.library="existing";}],[D("emptyLabel"),()=>{state.library="empty";}]])),button(T("Steam 참고 목록 새로고침"),()=>show(T("Steam 참고 목록 새로고침"),T("Steam 참고 목록 새로고침은 Steam 프리픽스와 연결된 Steam 라이브러리에서 appmanifest 파일을 다시 읽어 참고 목록을 갱신합니다."))));if(state.library){const status=el("div","sim-result");status.append(el("strong","",state.library==="existing"?"SteamLibrary · F:\\":"ExternalDrive · F:\\"));note(status,D(state.library==="existing"?"connected":"empty"));actionRow(status,button(T("연결 해제"),()=>{state.library=null;render();}));c.append(status);}else note(c,D("choose"));parent.append(c);const how=card(T("상태 확인"));note(how,T(map.views.storage.notes[2]));parent.append(how);};
  const exeView=parent=>{const c=card(T("EXE 실행 (베타)"));note(c,T(map.views.exe.notes[0]));actionRow(c,button(T("EXE 파일 선택"),()=>show(T("EXE 파일 선택"),D("fileHint"),['ClassicGame.exe','Setup.exe','WindowsUtility.exe'].map(file=>[file,()=>{state.exe=file;}]))),button(T("같은 프리픽스에서 실행"),()=>explain("exeLaunch"),"sim-primary"));c.querySelector('.sim-primary').disabled=!state.exe;if(state.exe)c.append(el("p","sim-file",state.exe));field(c,T("선택 그래픽 백엔드"),picker("exeRenderer",[["Wine",T("Wine 기본")],...['D3DMetal - NVIDIA','DXMT','DXVK','WineD3D'].map(x=>[x,x])],T("선택 그래픽 백엔드")));note(c,T(map.views.exe.notes[3]),"sim-important");parent.append(c);};
  const profilesView=parent=>{const c=card(T("게임 프로필"));field(c,T("게임 프로필"),(()=>{const s=el("select");s.setAttribute("aria-label",T("게임 프로필"));s.append(el("option","","HELLDIVERS 2 · App ID 553850"));return s;})());actionRow(c,button(T("루트 선택"),()=>show(T("루트 선택"),D("fileHint"),[["SteamLibrary / steamapps",()=>{state.profileRoot=true;}]])),button(T("프로필 권장값 복원"),()=>{state.profileRoot=false;render();}),button(T("설정 저장"),()=>explain("saved")));note(c,state.profileRoot?"SteamLibrary / steamapps":T("이 프로필이 적용될 설치의 매니페스트 루트 폴더를 선택하세요."));const launch=button(T("Steam 실행"),()=>explain("launch"),"sim-primary");launch.disabled=!state.profileRoot;c.append(launch);parent.append(c);};
  const inputView=parent=>{const c=card(T("게임 입력 및 macOS 단축키 보호"));note(c,T("변경한 설정은 다음 Steam 실행부터 적용됩니다."));note(c,T(map.views.input.notes[1]));toggle(c,T("게임이 전면일 때 macOS 포인터 숨기기 (베타)"),"pointer");toggle(c,T("게임용 보조키 매핑 사용"),"mapping");if(state.mapping){for(const [key,label]of [['command','Command'],['option','Option'],['control','Control']])field(c,label,picker(key,[["Ctrl","Ctrl"],["Alt","Alt"],["none",T("전달 안 함")]],label));note(c,T(map.views.input.notes[2]));}for(const [key,label]of [['quitKeys','게임 중 앱 종료·창 관리 단축키 차단'],['switchKeys','게임 중 앱 전환·검색 단축키 차단'],['spaces','게임 중 Mission Control·Spaces 키보드 단축키 차단'],['screenshots','게임 중 macOS 기본 스크린샷 단축키 차단']])toggle(c,T(label),key);note(c,"⌘Q · ⌘W · ⌘H · ⌘M / ⌘Tab · ⌘Space / Control + ↑↓←→ / ⌘⇧3·4·5·6");parent.append(c);awdlView(parent);};
  const awdlView=parent=>{const c=card("AWDL");toggle(c,"AWDL",'awdl');note(c,T(map.views.awdl.notes[2]),state.awdl?"":"sim-important");note(c,D("visionWarning"),"sim-important");actionRow(c,button("Vision Pro",()=>change("vision")),button(T("AWDL 상태 새로고침"),()=>show("AWDL",D("notice"))));parent.append(c);};
  const setupView=parent=>{const c=card(T("설정"));const steps=["앱 데이터 준비","Mac 상태 확인","ForgePlay Runtime","Steam 프리픽스","Steam 설치","Steam 로그인 및 라이브러리"];steps.forEach((s,i)=>{const row=el("div","sim-setup-row");row.append(el("span","",i<state.setup?"✓":String(i+1)),el("strong","",T(s)),el("small","",D(i<state.setup?"ready":"waiting")));if(i===state.setup)row.append(button(T("다음"),()=>{state.setup++;render();}));c.append(row);});if(state.setup===steps.length)c.append(button(T("Steam 실행 화면 열기"),()=>change("steam"),"sim-primary"));parent.append(c);};
  const diagnosticsView=parent=>{const c=card(T("문제 진단 (베타)"));note(c,D("result"));const cases=el("div","sim-choice-tabs");['caseLibrary','caseUpdate','caseRuntime'].forEach((key,i)=>{const b=button(D(key),()=>{state.analysis=i;render();},state.analysis===i?'sim-selected':'');b.setAttribute('aria-pressed',String(state.analysis===i));cases.append(b);});c.append(cases);actionRow(c,button(T("최근 로그 다시 분석"),()=>{state.analysis=state.analysis??0;render();}),button(T("AI 로컬 분석 전 미리보기"),()=>explain("ai")),button(T("지원 번들 생성"),()=>explain("bundle")));if(state.analysis!==null){const r=el("div","sim-result");r.append(el("strong","",D("result")));const texts=[T(map.views.storage.notes[2]),T(map.views.steam.notes[2]),T(map.views.components.notes[0])];note(r,texts[state.analysis]);r.append(button(name(['storage','prefix','components'][state.analysis]),()=>change(['storage','prefix','components'][state.analysis])));c.append(r);}parent.append(c);};
  const catalogView=parent=>{const c=card(T("게임 호환성 DB"));note(c,D("catalog"));const search=el("input");search.type="search";search.placeholder=W("compat.searchPlaceholder");search.setAttribute("aria-label",W("compat.searchPlaceholder"));const list=el("div","sim-catalog");const populate=()=>{list.replaceChildren();if(!catalog){note(list,D("waiting"));return;}catalog.games.filter(g=>Object.values(g.titles).some(s=>s.toLocaleLowerCase().includes(search.value.toLocaleLowerCase()))).forEach(g=>{const reports=catalog.reports.filter(r=>r.gameId===g.id);const result=window.ForgePlayWebCatalog.summarize(reports,release?.marketingVersion);const desc=window.ForgePlayWebCatalog.describe(result,W);const row=el("details");row.dataset.tone=result.tone;const heading=el("summary");heading.append(el("strong","",locale()==='ko'?g.titles.ko:g.titles.en),el("span","",`${desc.statusText} · ${desc.versionText}`));row.append(heading);window.ForgePlayWebCatalog.sortReports(reports).forEach(r=>{const text=r.notes?.[locale()]||r.notes?.en||W("compat.notePlayable");note(row,`ForgePlay ${r.forgePlayVersion||'—'} — ${text}`);});list.append(row);});};search.addEventListener("input",populate);c.append(search,list);populate();parent.append(c);};
  const dashboardView=parent=>{const c=card(T("대시보드"));note(c,D("badge"));const grid=el("div","sim-status-grid");for(const label of ["Mac 상태","ForgePlay Runtime","Steam 프리픽스","Windows용 Steam"]){const tile=el("div");tile.append(el("small","",T(label)),el("strong","",D("ready")));grid.append(tile);}c.append(grid);actionRow(c,button(T("상태 새로고침"),()=>show(T("상태 새로고침"),D("notice"))),button(T("Steam 실행"),()=>change("steam"),"sim-primary"),button(name('diagnostics'),()=>change('diagnostics')));parent.append(c);};
  const preferencesView=parent=>{const c=card(T("앱 언어"));const select=el("select");const names={ko:"한국어",en:"English",de:"Deutsch",es:"Español",fr:"Français",ja:"日本語","zh-Hans":"简体中文","zh-Hant":"繁體中文"};select.setAttribute('aria-label',T('앱 언어'));locales.forEach(l=>{const o=el("option","",names[l]);o.value=l;o.selected=l===locale();select.append(o);});select.addEventListener("change",()=>{const master=document.querySelector('[data-language-select]');master.value=select.value;master.dispatchEvent(new Event('change',{bubbles:true}));});field(c,T("앱 언어"),select);field(c,T("화면 스타일"),picker('theme',[['system',T('시스템')],['dark',T('다크')],['light',T('라이트')]],T('화면 스타일')));actionRow(c,button(name('input'),()=>change('input')),button('AWDL',()=>change('awdl')));parent.append(c);};
  const prefixView=parent=>{const c=card(T("Steam 프리픽스"));note(c,T(map.views.prefix.notes[0]));field(c,T("동기화"),picker('sync',[['auto',T('자동')]],T('동기화')));actionRow(c,button(T("Steam 프리픽스 재생성"),()=>explain('rebuild')),button(T("설정 저장"),()=>explain('saved')));c.append(link(W('shared.navUpdates'),'updates.html?lang='+locale()+'#update-forgeplay-1-3-1-update'));parent.append(c);};
  const dataView=parent=>{const c=card(T("진단 및 데이터"));field(c,T("문제 분석 기록 보존"),picker('retention',[['7','7'],['30','30'],['90','90']],T('문제 분석 기록 보존')));note(c,T(map.views.data.notes[1]));actionRow(c,button(T("보존 설정 저장"),()=>explain('saved')),button(T("지금 정리"),()=>show(T("지금 정리"),D('notice'))),button(T("지원 번들 생성"),()=>explain('bundle')),button(T("게임 호환성 DB"),()=>change('catalog')));parent.append(c);};
  const componentsView=parent=>{const c=card(T("필수 구성요소 설치 도구"));note(c,T(map.views.components.notes[0]));const choices=el('div','sim-actions');['VC++','DirectX','.NET','OpenAL','XNA','PhysX'].forEach(label=>choices.append(button(label,()=>show(label,`${D('fileHint')} ${T(map.views.components.notes[0])}`))));c.append(choices);parent.append(c);};
  const appsView=parent=>{
    const c=card(name('apps'));
    const platforms=el('div','sim-actions');
    for(const [id,label] of [['mac','Mac'],['ipad','iPad'],['iphone','iPhone']]){
      const b=button(label,()=>{appPlatform=id;render();},appPlatform===id?'sim-selected':'');
      b.setAttribute('aria-pressed',String(appPlatform===id));platforms.append(b);
    }
    const search=el('input');search.type='search';search.setAttribute('aria-label',W('developerApps.title'));
    const list=el('div','sim-apps');
    const populate=()=>{
      list.replaceChildren();
      for(const app of appCatalog?.apps||[]){
        const summary=app.summaries?.[locale()]||app.summaries?.en||'';
        if(app.platform!==appPlatform||!(app.name+' '+summary).toLocaleLowerCase().includes(search.value.toLocaleLowerCase()))continue;
        const item=el('article');const icon=el('img');icon.src=app.artwork;icon.alt='';icon.width=36;icon.height=36;icon.loading='lazy';
        item.append(icon,el('strong','',app.name));note(item,summary);
        item.append(link(W(app.appStoreID?'developerApps.appStoreLink':'developerApps.homepageLink'),app.href));list.append(item);
      }
    };
    search.addEventListener('input',populate);populate();
    c.append(platforms,search,list,link(D('more'),'index.html?lang='+locale()+'#other-apps'));parent.append(c);
  };
  const infoView=parent=>{if(view==='apps'){appsView(parent);return;}const c=card(name(view));(map.views[view].notes||[]).forEach(k=>note(c,T(k)));if(view==='about'){note(c,`ForgePlay ${release?.marketingVersion||'1.3.1'} (${release?.buildNumber||5})`);actionRow(c,button(T("업데이트 확인"),()=>explain('updated')));c.append(link(D('more'),release?.releaseURL||'https://github.com/Facta-Leopard/ForgePlay/releases/latest'));}if(view==='why')c.append(link(D('more'),'why.html?lang='+locale()));if(view==='sponsors')c.append(link('GitHub Sponsors','https://github.com/sponsors/facta-leopard'));parent.append(c);};
  const visionView=parent=>{const c=card(D('visionTitle'));const img=el('img');img.src=`site-assets/guide/vision/ultrawide-${photo+1}.jpg`;img.alt=D('visionBody');c.append(img);actionRow(c,button('1',()=>{photo=0;render();}),button('2',()=>{photo=1;render();}));note(c,D('visionBody'));note(c,D('visionWarning'),'sim-important');toggle(c,'AWDL','awdl');if(!state.awdl)note(c,D('visionWarning'),'sim-important');actionRow(c,button(D('visionLink'),()=>change('awdl')));parent.append(c);};
  const render=()=>{
    if(!root||!map)return;
    const focused=document.activeElement;
    const focusId=root.contains(focused)?focused.id:null;
    const focusView=root.contains(focused)?focused.dataset.view:null;
    root.setAttribute('aria-label',D('title'));
    const shell=root.querySelector('.sim-window');shell.classList.toggle('sim-light',state.theme==='light');
    root.querySelector('[data-sim-title]').textContent=name(view);root.querySelector('[data-sim-badge]').textContent=D('badge');root.querySelector('[data-sim-notice]').textContent=D('notice');root.querySelector('[data-sim-reset]').textContent=D('reset');root.querySelector('[data-sim-mode-demo]').textContent=D('interact');root.querySelector('[data-sim-mode-capture]').textContent=D('capture');
    root.querySelector('[data-sim-mode-demo]').setAttribute('aria-pressed',String(mode==='demo'));root.querySelector('[data-sim-mode-capture]').setAttribute('aria-pressed',String(mode==='capture'));root.querySelector('[data-sim-mode-capture]').disabled=view==='vision';
    const navigation=root.querySelector('[data-sim-nav]');navigation.replaceChildren();nav.forEach(id=>{const b=button('',()=>change(id),'sim-nav-item');const active=id===view||(id==='steam'&&steam.includes(view))||(id==='general'&&prefs.includes(view));b.setAttribute('aria-pressed',String(active));b.dataset.view=id;b.append(el('span','sim-nav-icon',id==='vision'?'◉':map.views[id].icon),el('span','',name(id)));navigation.append(b);});
    const sub=root.querySelector('[data-sim-subnav]');sub.replaceChildren();const family=steam.includes(view)?steam:prefs.includes(view)?prefs:[];family.forEach(id=>{const b=button(name(id),()=>change(id));b.setAttribute('aria-pressed',String(id===view));sub.append(b);});sub.hidden=!family.length;
    const content=root.querySelector('[data-sim-content]');content.replaceChildren();content.dataset.view=view;
    if(mode==='capture'){const frame=el('div','sim-capture');const img=el('img');img.src=`site-assets/guide/screens/${locale()}/${view==='steam'&&state.fg?'fg':view}.jpg`;img.alt=name(view);frame.append(img);content.append(frame);note(content,D('shot'));}else{({setup:setupView,steam:steamView,fg:p=>p.append(fgCard()),storage:storageView,components:componentsView,profiles:profilesView,exe:exeView,catalog:catalogView,dashboard:dashboardView,diagnostics:diagnosticsView,general:preferencesView,input:inputView,awdl:awdlView,prefix:prefixView,data:dataView,vision:visionView}[view]||infoView)(content);}
    const help=root.querySelector('[data-sim-help]');help.replaceChildren();help.append(el('h3','',D('learn')));if(view==='vision'){note(help,D('visionBody'));note(help,D('visionWarning'));}else{for(const key of map.views[view].notes)note(help,T(key));}
    root.querySelector('[data-sim-update]').textContent=T('업데이트 확인');
    if(focusId)document.getElementById(focusId)?.focus({preventScroll:true});
    else if(focusView)root.querySelector(`[data-sim-nav] [data-view="${focusView}"]`)?.focus({preventScroll:true});
  };
  const renderVision=()=>{visionSections.forEach(section=>{for(const key of ['visionTitle','visionBody','visionWarning','visionCredit','visionLink'])section.querySelectorAll(`[data-demo-text="${key}"]`).forEach(n=>n.textContent=D(key));section.querySelectorAll('[data-vision-photo]').forEach((img,i)=>{img.alt=`${D('visionTitle')} ${i+1}`;});});};
  Promise.all([root?json('site-data/guide-app-map.json'):null,root?json('site-data/guide-ui.json'):null,json('site-data/guide-demo.json')]).then(async([m,t,d])=>{
    map=m;translations=t;demos=d;renderVision();if(!root)return;
    root.replaceChildren();const sectionHeader=el('header','sim-intro');sectionHeader.append(el('h2','',D('title')),el('p','',D('lead')));root.append(sectionHeader);
    const shell=el('div','sim-window');const bar=el('div','sim-titlebar');const lights=el('span','sim-traffic','● ● ●');lights.setAttribute('aria-hidden','true');const title=el('strong');title.dataset.simTitle='';const badge=el('span','sim-demo-badge');badge.dataset.simBadge='';bar.append(lights,title,badge);shell.append(bar);
    const layout=el('div','sim-layout');const sidebar=el('aside','sim-sidebar');const brand=el('div','sim-brand');const icon=el('img');icon.src='site-assets/forgeplay-icon.png';icon.width=36;icon.height=36;icon.alt='';brand.append(icon,el('strong','','ForgePlay'));const navigation=el('nav');navigation.dataset.simNav='';const update=button('',()=>explain('updated'),'sim-update');update.dataset.simUpdate='';sidebar.append(brand,navigation,el('small','','ForgePlay 1.3.1 (5)'),update);layout.append(sidebar);
    const body=el('div','sim-body');const toolbar=el('div','sim-toolbar');const demo=button('',()=>{mode='demo';render();});demo.dataset.simModeDemo='';const capture=button('',()=>{mode='capture';render();});capture.dataset.simModeCapture='';const reset=button('',()=>{state=initial();mode='demo';render();});reset.dataset.simReset='';toolbar.append(demo,capture,reset);const notice=el('p','sim-disclaimer');notice.dataset.simNotice='';const tabs=el('div','sim-subnav');tabs.dataset.simSubnav='';const content=el('div','sim-content');content.dataset.simContent='';body.append(toolbar,notice,tabs,content);layout.append(body);shell.append(layout);root.append(shell);const help=el('aside','sim-help');help.dataset.simHelp='';root.append(help);
    dialog=el('dialog','sim-dialog');dialog.setAttribute('aria-labelledby','sim-dialog-title');dialog.addEventListener('close',()=>{if(lastFocus?.isConnected)lastFocus.focus();});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});root.append(dialog);
    const applyHash=()=>{const id=location.hash.replace('#app-','');if(map.views[id]||id==='vision'){view=id;mode='demo';}render();};window.addEventListener('hashchange',applyHash);applyHash();
    document.addEventListener('forgeplay:localechange',()=>{sectionHeader.firstChild.textContent=D('title');sectionHeader.lastChild.textContent=D('lead');renderVision();render();});
    // Each public data source is optional to the other learning screens.
    const results=await Promise.allSettled([window.ForgePlayCurrentRelease?.ready,window.ForgePlayWebCatalog?.load(),json('site-data/developer-apps.json')]);
    [release,catalog,appCatalog]=results.map(result=>result.status==='fulfilled'?result.value:null);render();
  }).catch(()=>{if(root)root.textContent='ForgePlay guide could not be loaded. Please reload.';});
  if(!root)document.addEventListener('forgeplay:localechange',()=>{if(demos)renderVision();});
})();
