window.ForgePlaySupporterCopy = Object.freeze({
  ko: {
    pageTitle: "ForgePlay — 후원기록", meta: "ForgePlay의 독립적인 개발과 공개된 기술을 지지해 주신 후원자분들께 감사드립니다.", eyebrow: "후원기록", title: "ForgePlay를 응원해 주셔서", titleAccent: "감사합니다.", lead: "독립적인 개발과 공개된 기술을 지지해 주신 분들. 여러분의 응원을 이곳에 기록합니다.", sponsor: "GitHub에서 후원하기", remember: "한 분 한 분의 응원을 기억합니다.", supporters: "후원자", thankLabel: "THANK YOU", thanks: "ForgePlay를 응원해 주셔서 감사합니다", thankShort: "후원해 주셔서 감사합니다", nameNote: "보내주신 응원에 감사의 마음을 전합니다.", hover: "마우스를 올리면 잠시 멈춥니다", invite: "함께해 주신 이름을, 이곳과 ForgePlay 런처에 남깁니다.", join: "후원으로 함께하기", allNames: "움직이지 않는 전체 명단 보기", enterprise: "엔터프라이즈 후원자", enterpriseWelcome: "첫 엔터프라이즈 후원자를 기다립니다.", enterpriseEmpty: "아직 등록된 엔터프라이즈 후원자가 없습니다.", signoff: "금액과 관계없이, 보내주신 모든 응원에 감사드립니다.", launcherTitle: "앱을 열 때도, 감사의 마음을 전합니다.", launcherBody: "런처의 감사 자막에서도 사용할 수 있도록, 같은 공개 명단을 제공합니다.", mockNote: "감사 자막의 표시 예시이며, 실제 런처가 실행되는 화면은 아닙니다.", mockLabel: "표시 예시", mockTagline: "Mac에서 계속되는 플레이.", openApp: "앱 열기", privacyTitle: "보내주신 응원을 기억합니다.", privacyBody: "후원자가 정한 표시이름을 우선 사용합니다. 별도 표시이름이 없으면 GitHub 아이디를 표시하며, 개인별 후원 금액은 공개하지 않습니다.", loading: "명단을 불러오는 중", failed: "명단을 불러오지 못했습니다", count: "후원자 {count}명", empty: "후원해 주신 모든 분께 감사드립니다.", pause: "자막 멈추기", play: "자막 재생", reduced: "정지 표시 중"
  },
  en: {
    pageTitle: "ForgePlay — Supporters", meta: "Thank you to everyone supporting ForgePlay’s independent development and open technology.", eyebrow: "SUPPORTER CREDITS", title: "Thank you for", titleAccent: "supporting ForgePlay.", lead: "To everyone who supports independent development and open technology: this page is for you.", sponsor: "Sponsor on GitHub", remember: "Every supporter matters.", supporters: "Supporters", thankLabel: "THANK YOU", thanks: "Thank you for supporting ForgePlay", thankShort: "Thank you for your support", nameNote: "We appreciate the support you have given us.", hover: "Hover to pause", invite: "Your name has a place here and in the ForgePlay launcher.", join: "Become a supporter", allNames: "View the full, stationary list", enterprise: "Enterprise supporters", enterpriseWelcome: "Be our first enterprise supporter.", enterpriseEmpty: "No enterprise supporters are listed yet.", signoff: "Whatever the amount, every contribution is appreciated.", launcherTitle: "A thank-you when you open the app, too.", launcherBody: "The same public name list is available for integration with the launcher’s thank-you ticker.", mockNote: "Illustration of the thank-you ticker, not a live launcher.", mockLabel: "Illustration", mockTagline: "Your games, on Mac.", openApp: "Open app", privacyTitle: "Recognized by the name you choose.", privacyBody: "We use your preferred display name, or your GitHub username if none is provided. Individual donation amounts are not shown.", loading: "Loading supporters", failed: "The supporter list could not be loaded", count: "{count} supporters", empty: "Thank you to everyone who supports ForgePlay.", pause: "Pause ticker", play: "Play ticker", reduced: "Motion paused"
  },
  de: {
    pageTitle: "ForgePlay — Unterstützer", meta: "Danke an alle, die ForgePlays unabhängige Entwicklung und offene Technologie unterstützen.", eyebrow: "UNSERE UNTERSTÜTZER", title: "Danke, dass ihr", titleAccent: "ForgePlay unterstützt.", lead: "Für alle, die unabhängige Entwicklung und offene Technologie unterstützen: Hier würdigen wir euren Beitrag.", sponsor: "Auf GitHub unterstützen", remember: "Jede Unterstützung zählt.", supporters: "Unterstützer", thankLabel: "DANKE", thanks: "Danke, dass ihr ForgePlay unterstützt", thankShort: "Danke für eure Unterstützung", nameNote: "Wir danken euch für eure Unterstützung.", hover: "Zum Anhalten Maus darüber bewegen", invite: "Euer Name findet hier und im ForgePlay-Launcher seinen Platz.", join: "ForgePlay unterstützen", allNames: "Vollständige Liste ohne Bewegung anzeigen", enterprise: "Unternehmenssponsoren", enterpriseWelcome: "Werdet unser erster Unternehmenssponsor.", enterpriseEmpty: "Noch sind keine Unternehmenssponsoren eingetragen.", signoff: "Unabhängig vom Betrag: Wir schätzen jeden Beitrag.", launcherTitle: "Auch beim App-Start sagen wir Danke.", launcherBody: "Dieselbe öffentliche Namensliste steht für die Einbindung in die Dankes-Laufschrift des Launchers bereit.", mockNote: "Darstellungsbeispiel der Dankes-Laufschrift, kein laufender Launcher.", mockLabel: "Beispiel", mockTagline: "Eure Spiele auf dem Mac.", openApp: "App öffnen", privacyTitle: "Mit dem Namen, den ihr wählt.", privacyBody: "Wir verwenden den gewünschten Anzeigenamen oder, falls keiner angegeben ist, den GitHub-Namen. Einzelne Spendenbeträge werden nicht angezeigt.", loading: "Liste wird geladen", failed: "Die Unterstützerliste konnte nicht geladen werden", count: "{count} Unterstützer", empty: "Danke an alle, die ForgePlay unterstützen.", pause: "Laufschrift anhalten", play: "Laufschrift starten", reduced: "Bewegung angehalten"
  },
  es: {
    pageTitle: "ForgePlay — Patrocinadores", meta: "Gracias a quienes apoyan el desarrollo independiente y la tecnología abierta de ForgePlay.", eyebrow: "AGRADECIMIENTOS", title: "Gracias por", titleAccent: "apoyar ForgePlay.", lead: "A quienes apoyan el desarrollo independiente y la tecnología abierta: este espacio reconoce vuestra ayuda.", sponsor: "Patrocinar en GitHub", remember: "Cada apoyo cuenta.", supporters: "Patrocinadores", thankLabel: "GRACIAS", thanks: "Gracias por apoyar ForgePlay", thankShort: "Gracias por vuestro apoyo", nameNote: "Agradecemos el apoyo que nos habéis brindado.", hover: "Pasa el cursor para pausar", invite: "Vuestros nombres tienen un lugar aquí y en el lanzador de ForgePlay.", join: "Apoyar ForgePlay", allNames: "Ver la lista completa sin movimiento", enterprise: "Patrocinadores empresariales", enterpriseWelcome: "Sé nuestro primer patrocinador empresarial.", enterpriseEmpty: "Todavía no hay patrocinadores empresariales registrados.", signoff: "Agradecemos todas las aportaciones, sin importar el importe.", launcherTitle: "También os damos las gracias al abrir la app.", launcherBody: "La misma lista pública de nombres está disponible para integrarla en la banda de agradecimientos del lanzador.", mockNote: "Ejemplo de la banda de agradecimientos, no un lanzador en ejecución.", mockLabel: "Ejemplo", mockTagline: "Tus juegos, en Mac.", openApp: "Abrir app", privacyTitle: "El nombre que elijas.", privacyBody: "Mostramos el nombre elegido o, si no se indica, el nombre de usuario de GitHub. No mostramos los importes individuales de las donaciones.", loading: "Cargando la lista", failed: "No se ha podido cargar la lista de patrocinadores", count: "{count} patrocinadores", empty: "Gracias a todas las personas que apoyan ForgePlay.", pause: "Pausar banda", play: "Reanudar banda", reduced: "Movimiento detenido"
  },
  fr: {
    pageTitle: "ForgePlay — Soutiens", meta: "Merci à toutes les personnes qui soutiennent le développement indépendant et les technologies ouvertes de ForgePlay.", eyebrow: "NOS SOUTIENS", title: "Merci de", titleAccent: "soutenir ForgePlay.", lead: "À toutes les personnes qui soutiennent le développement indépendant et les technologies ouvertes : cette page vous est dédiée.", sponsor: "Soutenir sur GitHub", remember: "Chaque soutien compte.", supporters: "Soutiens", thankLabel: "MERCI", thanks: "Merci de soutenir ForgePlay", thankShort: "Merci pour votre soutien", nameNote: "Nous vous remercions pour votre soutien.", hover: "Survolez pour mettre en pause", invite: "Votre nom a sa place ici et dans le lanceur ForgePlay.", join: "Soutenir ForgePlay", allNames: "Afficher la liste complète sans défilement", enterprise: "Mécènes d’entreprise", enterpriseWelcome: "Devenez notre premier mécène d’entreprise.", enterpriseEmpty: "Aucun mécène d’entreprise n’est encore inscrit.", signoff: "Quel que soit le montant, chaque contribution compte.", launcherTitle: "Un merci aussi à l’ouverture de l’app.", launcherBody: "La même liste publique de noms est disponible pour être intégrée au bandeau de remerciements du lanceur.", mockNote: "Exemple du bandeau de remerciements, et non un lanceur en cours d’exécution.", mockLabel: "Exemple", mockTagline: "Vos jeux, sur Mac.", openApp: "Ouvrir l’app", privacyTitle: "Le nom que vous choisissez.", privacyBody: "Nous utilisons le nom d’affichage choisi ou, à défaut, votre identifiant GitHub. Le montant des contributions individuelles n’est pas affiché.", loading: "Chargement de la liste", failed: "La liste des soutiens n’a pas pu être chargée", count: "{count} soutiens", empty: "Merci à toutes les personnes qui soutiennent ForgePlay.", pause: "Arrêter le défilement", play: "Reprendre le défilement", reduced: "Défilement arrêté"
  },
  ja: {
    pageTitle: "ForgePlay — ご支援者", meta: "ForgePlayの独立した開発とオープンな技術を支えてくださる皆さまに感謝します。", eyebrow: "ご支援者", title: "ForgePlayへの応援、", titleAccent: "ありがとうございます。", lead: "独立した開発とオープンな技術を支えてくださる皆さま。そのご支援をここに記します。", sponsor: "GitHubで支援する", remember: "一人ひとりのご支援に感謝します。", supporters: "ご支援者", thankLabel: "THANK YOU", thanks: "ForgePlayへのご支援ありがとうございます", thankShort: "ご支援ありがとうございます", nameNote: "皆さまのご支援に感謝いたします。", hover: "マウスを重ねると一時停止します", invite: "ご支援者のお名前を、このページとForgePlayランチャーに表示します。", join: "ForgePlayを支援する", allNames: "スクロールしない一覧を表示", enterprise: "エンタープライズスポンサー", enterpriseWelcome: "最初のエンタープライズスポンサーをお待ちしています。", enterpriseEmpty: "登録されているエンタープライズスポンサーはまだありません。", signoff: "金額にかかわらず、すべてのご支援に感謝します。", launcherTitle: "アプリを開くときにも、感謝を伝えます。", launcherBody: "ランチャーの感謝テロップにも連携できるよう、同じ公開名簿を提供しています。", mockNote: "感謝のテロップの表示例です。実際に動作するランチャーではありません。", mockLabel: "表示例", mockTagline: "Macでも、ゲームの続きを。", openApp: "アプリを開く", privacyTitle: "お選びいただいた名前で。", privacyBody: "指定された表示名を優先し、未指定の場合はGitHubのユーザー名を表示します。個別の支援金額は公開しません。", loading: "一覧を読み込み中", failed: "支援者一覧を読み込めませんでした", count: "ご支援者 {count}名", empty: "ForgePlayを支えてくださるすべての皆さまに感謝します。", pause: "テロップを停止", play: "テロップを再生", reduced: "停止表示中"
  },
  "zh-Hans": {
    pageTitle: "ForgePlay — 赞助记录", meta: "感谢支持 ForgePlay 独立开发与开放技术的每一位赞助者。", eyebrow: "赞助记录", title: "感谢你", titleAccent: "支持 ForgePlay。", lead: "致支持独立开发与开放技术的每一位朋友：我们在这里记录你们的支持。", sponsor: "在 GitHub 上赞助", remember: "每一份支持，我们都铭记在心。", supporters: "赞助者", thankLabel: "感谢支持", thanks: "感谢你支持 ForgePlay", thankShort: "感谢你的支持", nameNote: "感谢大家给予的支持。", hover: "悬停可暂停", invite: "你的名字将出现在这里及 ForgePlay 启动器中。", join: "赞助 ForgePlay", allNames: "查看不滚动的完整名单", enterprise: "企业赞助者", enterpriseWelcome: "期待第一位企业赞助者。", enterpriseEmpty: "目前尚无登记的企业赞助者。", signoff: "无论金额大小，我们都感谢每一份支持。", launcherTitle: "打开应用时，也向你致谢。", launcherBody: "我们提供同一份公开名单，供启动器的感谢滚动字幕接入使用。", mockNote: "这是感谢字幕的显示示意，并非正在运行的启动器。", mockLabel: "显示示意", mockTagline: "在 Mac 上继续游戏。", openApp: "打开应用", privacyTitle: "以你选择的名字致谢。", privacyBody: "优先使用你指定的显示名称，未指定时使用 GitHub 用户名。不公开个人赞助金额。", loading: "正在加载名单", failed: "无法加载赞助者名单", count: "{count} 位赞助者", empty: "感谢所有支持 ForgePlay 的朋友。", pause: "暂停字幕", play: "播放字幕", reduced: "已停止滚动"
  },
  "zh-Hant": {
    pageTitle: "ForgePlay — 贊助紀錄", meta: "感謝支持 ForgePlay 獨立開發與開放技術的每一位贊助者。", eyebrow: "贊助紀錄", title: "感謝你", titleAccent: "支持 ForgePlay。", lead: "致支持獨立開發與開放技術的每一位朋友：我們在這裡記錄你們的支持。", sponsor: "在 GitHub 上贊助", remember: "每一份支持，我們都銘記在心。", supporters: "贊助者", thankLabel: "感謝支持", thanks: "感謝你支持 ForgePlay", thankShort: "感謝你的支持", nameNote: "感謝大家給予的支持。", hover: "移入游標即可暫停", invite: "你的名字將出現在這裡及 ForgePlay 啟動器中。", join: "贊助 ForgePlay", allNames: "查看不捲動的完整名單", enterprise: "企業贊助者", enterpriseWelcome: "期待第一位企業贊助者。", enterpriseEmpty: "目前尚無登記的企業贊助者。", signoff: "無論金額大小，我們都感謝每一份支持。", launcherTitle: "開啟 App 時，也向你致謝。", launcherBody: "我們提供同一份公開名單，供啟動器的感謝跑馬燈串接使用。", mockNote: "這是感謝跑馬燈的顯示示意，並非正在執行的啟動器。", mockLabel: "顯示示意", mockTagline: "在 Mac 上繼續遊戲。", openApp: "開啟 App", privacyTitle: "以你選擇的名字致謝。", privacyBody: "優先使用你指定的顯示名稱，未指定時使用 GitHub 使用者名稱。不公開個人贊助金額。", loading: "正在載入名單", failed: "無法載入贊助者名單", count: "{count} 位贊助者", empty: "感謝所有支持 ForgePlay 的朋友。", pause: "暫停跑馬燈", play: "播放跑馬燈", reduced: "已停止捲動"
  }
});
